# Avatar Framer Config
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ATI-NTC Residence Hall Open House 2024
description: >- # this means to ignore newlines"
  Frame.

# Copy
# Fill in your copy for the title and steps here
# 
title-text: "ATI-NTC Residence Hall Open House 2024"
step-1: "Upload your picture or another square image below."
step-2: "Use the photo tools to scale, rotate, and move your image over the preview."
step-3: "Select your frame."
step-4: "Download your new profile image!"
step-5: "Post on social media using the hashtag #TeamBartlet."
footer-text: "&copy; 2024 Francis Dominic Fajardo. All rights reserved."
footer-link: https://fofajardo.github.io/

# Buttons and upload form
# 
upload-text: "Drop files here or click to upload."
download-button-text: "Download profile picture"

# Logo & Favicon
# 
logo: "logo.png"
favicon: "favicon.ico"

# Open Graph and Twitter Cards
#
og-title: ATI-NTC Residence Hall Open House 2024
og-description: ATI-NTC Residence Hall Open House 2024
og-url: https://framenatin.pages.dev/openhouse2024/
og-image: "og-image.png"
og-image-width: 1280
og-image-height: 640
twitter-card: summary_large_image
twitter-description: "Create your framed profile picture for the ATI-NTC Residence Hall Open House 2024"
twitter-image: "og-image.png"
twitter-handle: ""

caption-lines:
- Sinong pipiliin mo, DoTA o Ako? ğŸ¥º Ba't hindi both, eh nasa ATI naman ako! ğŸ˜‹<br>
- Na-miss mo ğŸ«µğŸ˜³ na ba ang ğŸ”¥COMSHOP VIBESğŸ”¥ ?? ğŸ™ˆğŸ¤” Tara na at sumama sa trip down memory lane at i-experience muli ang asim ğŸ¤¢, ang soundtripğŸ˜, ang foodtripğŸ˜›, at ang kulitanğŸ¤­ sa comshop!<br>
- Ako nga pala si (Insert Name Here) at inaanyayahan kayong pumunta na dito lamang sa ATI-NTC Residence Hall sa March 14, 2024 para sa aming Open House na may temang COMPUTER SHOP! May palaro, may pakain, tugtugan, at kung anu-ano pa!<br>
- Register na kayo sa CS 1.6 tournament namin! https://bit.ly/ATI_OH24CS <br>
- Trip mo 'yung frame? https://framenatin.pages.dev/openhouse2024/ <br>
- Ano pang hinihintay mo? ğŸ«µğŸ¤¨ Kita-kits! ğŸ¥°ğŸ˜‹ğŸ”¥â¤ï¸ <br>
- >-
    #IbaAngSayaSaATI <br>
    #ATIOpenHouse <br>
    #ATInTo <br>
    #NgitingATI <br>
    #MabuhayATI <br>
    #ATILagingMayWiFi <br>

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
# 
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - "*.config.js"
  - "*.config.json"
  - "package*.json"
